### ISSUE TITLE
Add properties that can be forwarded to the sub-components directly

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-date-time-picker#3]
- datePlaceholder
- timePlaceholder
- step (time picker resolution)
- initialPosition (Only affects the date picker)
- showWeekNumbers

```js
// Example observer
__stepChanged(step, __timePicker) {
  if (__timePicker) {
    __timePicker.step = step;
  }
}
```

**Comment by Haprog** [comment]
As part of this I will also add:
- `label` (for custom field)
- `disabled` (for date picker and time picker)
- `readonly` (for date picker and time picker)
