### ISSUE TITLE
Tabbing does not work in Chrome

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-date-time-picker#9]
https://cdn.vaadin.com/vaadin-date-time-picker/1.0.0-alpha1/demo/#date-time-picker-basic-demos

1. Focus date input
2. Tab to time input
3. Shift + Tab back to date input → focus stays in the time input

Chrome, macOS

Works as expected in Safari, macOS.

**Comment by Haprog** [comment]
Should work after a new patch version of custom field is released with this fix https://github.com/vaadin/vaadin-custom-field/commit/fd1099aee29f8acf045c052dd75c72d94b9dd296 (need to update custom field dependency version in date time picker then)
